### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by megamattron** [zserge/anvil#13]
This seems really cool, but I had a couple questions. Sorry to put these in an issue, wasn't sure how else to ask:

1. How do you handle resource overrides? By screen dimensions, landscape vs. portrait, etc.
2. Have you considered connecting the reactivity all the way back to the server, similar to how Facebook is doing it in React native? So a view might be connected all the way back to a json path on a server somewhere and a change on the server could propagate automatically all the way to the UI.

Thanks for doing this project, great to have some strong alternative views on Android dev!

**Comment by zserge** [comment]
Hi,

Asking here is absolutely fine, I will just use the "question" tag for such issues.

1. Overridden resources work in the same way as they would work with XMLs - you still can use `text(R.string.foo)` and your localized string would be set as a text. You still can use values.xml, colors.xml and friends. One thing that is different is layouts (because there is no more XML layouts).
Anvil provides a helper function `isPortrait()` so you can have two layout functions in code for landscape and portrait and toggle them with a ternary operator or a simple if/then/else. There is also an `R()` function that returns current `Resources` instance for the view context, so you can add "responsiveness" to your UI components depending on any suitable constraints (size, dpi, android version, language, phone model, day of week, user mood etc).

2. The idea is brilliant, but I don't think it should be part of Anvil core (because it will put the INTERNET permission into every Anvil app). But it would be a very helpful library on top of Anvil, great alternative to RetroFit. Currently I do it all manually - make an okhttp request, in the callback update the values and cache them locally, finally call Anvil.render().
