### ISSUE TITLE
Adding anvil to local project causes gradle build to fail

### ISSUE THREAD

**Issue by corbt** [zserge/anvil#21]
This likely isn't a real issue, and I'm probably doing something wrong, but I thought I'd pass it on.

When I copy the anvil project to a subdirectory of my project and add it as a dependency (in dependencies I add `compile project(':libs:anvil:library')`), my gradle build fails with the following error:

```
12:04:01.150 [ERROR] [org.gradle.BuildExceptionReporter] Script '/Users/kyle/proj/android-emberall/libs/anvil/library/publish.gradle' line: 8
12:04:01.150 [ERROR] [org.gradle.BuildExceptionReporter]
12:04:01.151 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
12:04:01.152 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred evaluating script.
12:04:01.152 [ERROR] [org.gradle.BuildExceptionReporter] > org.gradle.api.internal.project.ProjectInternal.getPluginManager()Lorg/gradle/api/internal/plugins/PluginManagerInternal;
```

I've experimentally determined that commenting out either `apply from: 'publish.gradle'` or the line in publish.gradle `apply plugin: 'com.github.dcendents.android-maven'` make this issue go away, and that's what I'm doing right now. But I wonder if it's necessary to include the publishing script in the same build.gradle, as that may make it harder for people to use experimental versions of the library.

**Comment by zserge** [comment]
In the new Anvil (anvil-forge branch) I would recommend running `gradle build publishToMavenLocal` instead of including it as a subproject:

```
repositories {
  mavenLocal()
  jcenter()
}
dependencies {
  compile 'co.trikita:anvil:......'
}
```

So your locally built custom (or debug) variant of Anvil would be taken if you did 'publishToMavenLocal', otherwise the one from the JCenter would be used.

Of course later you can just remove the `anvil` directory tree from the `$HOME/.m2/repository/co/trikita/anvil` (which is where your locally published maven artifacts are stored) and it will use the official published version from the JCenter.

**Comment by zserge** [comment]
Anvil 0.1.x should not be used as a local project, instead it should be installed to mavenLocal if built from sources, so this issue shouldn't be relevant anymore
