### ISSUE TITLE
BaseDSL.xml() not exposed

### ISSUE THREAD

**Issue by samtstern** [zserge/anvil#37]
Using version 0.1.2, is that the latest?  Is XML coming in a future jcenter release?

**Comment by zserge** [comment]
Yes, 0.1.2 is the latest published on jcenter. XML feature is in the `tip`, not available as a maven artifact yet.

It's very hard to promote Anvil, so before every release I try to come up with some blog post and spread the word on reddit etc. That's why it takes a bit more time to prepare a release version that just set a git tag and push. Sorry about that, I will try to make an update this week.

**Comment by zserge** [comment]
Ok, Anvil 0.2.0 is finally published on jcenter and mavenCentral. It has `xml` and `withId` functions included.
