### ISSUE TITLE
View not getting refresh on data changes from different thread

### ISSUE THREAD

**Issue by ripal** [zserge/anvil#73]
Hi Friends,

I am using BLE library and each callbacks I am getting to front side is managed in different thread by BLE. Upon value change respected to callbacks, my binding view is not getting update. I have tried to place runonUIThread and still no luck. So it seems that whenever thread switching happens, binding view is not getting update on value change. On same thread or worker thread created on activity, binding is working perfect.

Example:

`withId(R.id.txtTemperature, () -> {
                        DSL.text(State.getInstance().temperature);
                    });`

callbacks on thread that created by BLE to return value  [ _Not Working_ ]

`@Override
    public void onTemperatureDataReceived(final double temperatureValue) {
        State.getInstance().temperature = temperatureValue
    }`

placing runOnUiThread [ _Not Working_ ]

`@Override
    public void onTemperatureDataReceived(final double temperatureValue) {
              runOnUiThread(new Runnable() {
              @Override
                  public void run() {
                        State.getInstance().temperature = temperatureValue
                  }
              });  
    }`

As you see above example, on state values updating, my textview is not reacting to it. It shows initial old values.

**Comment by zserge** [comment]
@ripal The only way to update views in Anvil is to call `Anvil.render()`. It can be called from other threads, then it will be posted to the UI thread handler. To save developer's and lines of code, Anvil.render() is called automatically in UI listeners (such as onClick, onTouch, ....) because in most cases user interaction changes something in the app and the UI should be updated.

In you case state is changed asynchronously, so you have to call Anvil.render() manually. It will cause all visible views to update (lazily) their attributes.

**Comment by ripal** [comment]
@zserge : thank you very much for your support. Appreciated. :+1:
