### ISSUE TITLE
How to deal with custom view?

### ISSUE THREAD

**Issue by devangazoi** [zserge/anvil#74]
Hello Folks,

I have already created custom view for ECG graph and try to convert it in Anvil but I am not getting idea about how to deal with custom view in Anvil so please it's possible then guide me to covert my already developed custom view in Anvil.

Thanks,
Devang

**Comment by zserge** [comment]
@devangazoi Your custom view exists for a purpose and there's nothing wrong with it. That's why there is no special need to artificially rewrite it to fit Anvil world.

You can include custom views into the hierarchy and you can call its methods directly inside the init block:

```
v(MyCustomView.class, () -> {
  init(() -> {
    MyCustomView myView = Anvil.currentView();
    myView.setSomeData(...);
    myView.setSomeListener(() -> {
    });
  });
});
```

In fact, in Anvil DSL `button(...)` function is the same as `v(Button.class, ...)` and `init` allows you to run code only once when the view is inflated, so it won't affect the performance.

**Comment by devangazoi** [comment]
Thank you very much.
