### ISSUE TITLE
Anvil doesn't work well with swiperefreshlayout after first render cycle

### ISSUE THREAD

**Issue by amoikevin** [zserge/anvil#97]
at the first cycle,the order of SRL's children is [CircleImageView,CustomView].
however,the order changes to [CustomView,CircleImageView] after that,but the viewIndex of the CustomView's node is 1.

**Comment by zserge** [comment]
I've recently added a method `skip()` aimed to ignore all the child views created outside of Anvil.

I was able to reproduce the issue you're describing, and with the new `skip()` method an example would look like this:

```java
    private class TestSwipeRefreshLayout extends RenderableView {
        private boolean mRefreshing;
        public TestSwipeRefreshLayout(Context c) {
            super(c);
        }
        public void view() {
            swipeRefreshLayout(() -> {
                size(FILL, FILL);
                onRefresh(() -> {
                    mRefreshing = true;
                    postDelayed(() -> {
                        mRefreshing = false;
                        Anvil.render();
                    }, 3000);
                });
                refreshing(mRefreshing);
                skip();
                textView(() -> {
                    size(FILL, FILL);
                    text(mRefreshing ? "refreshing" : "done");
                });
                skip();
            });
        }
    }
```

I had to use skip() twice, because as you've stated initially CircleImageView is placed before the child view, then it's placed after it.

Ideally, `skip()` should be called from inside the `swipeRefreshLayout()` function before and after calling the child renderable, but that would require adding some quirks to the DSL generator, which I would prefer to do after we release Anvil 0.5.0.

**Comment by amoikevin** [comment]
now it works
